log: {disabled: false, level: info, timestamp: true}
experimental:
  clash_api:
    external_controller: 192.168.31.1:9090
    external_ui: /etc/sing-box/ui
    secret: ""
    external_ui_download_detour: DirectConn
    default_mode: rule
    external_ui_download_url: "{mirror_url}/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip"
  cache_file: {enabled: true, path: /etc/sing-box/cache.db}
dns:
  servers:
    - {tag: dns_local, type: https, server: https://223.5.5.5/dns-query, detour: DirectConn}
    - {tag: dns_proxy, type: https, server: 8.8.8.8, detour: DNS}
    - {tag: dns_jp, type: https, server: 8.8.8.8, detour: Auto-JP }
    - {tag: dns_tailscale,type: tailscale, endpoint: ts-node}
    - {tag: fakeip, type: fakeip, inet4_range: 198.18.0.0/15, inet6_range: fc00::/18}
  rules:
    - {clash_mode: Direct, server: dns_local}
    - {clash_mode: Global, server: dns_proxy}
    - {rule_set: geosite-cryptocurrency, server: dns_jp }
    - {domain_suffix: [ts.net],server: dns_tailscale}
    - {rule_set: geosite-cn, server: dns_local}
    - {rule_set: geosite-geolocation-!cn, server: dns_proxy}
  final: dns_proxy
  strategy: prefer_ipv4
  disable_cache: false
  disable_expire: false
  independent_cache: true
  client_subnet: 223.5.5.5/24
inbounds:
  - {type: tproxy, tag: tproxy-in, listen: "::", listen_port: 7895, udp_timeout: 1m}
outbounds:
  - {tag: Test, type: selector, outbounds: [AAA]}
  - {tag: Proxy, type: selector, outbounds: [DIY-Node, Auto-HK, Auto-JP, Auto-US, Auto-SG, Auto-TW, Auto-KR, Select, HK, JP, DirectConn], interrupt_exist_connections: true}
  - {tag: DNS, type: selector, outbounds: [Proxy, Auto-HK, Auto-JP, DIY-Node], interrupt_exist_connections: true}
  - {tag: YouTube, type: selector, outbounds: [Proxy, DIY-Node, Auto-HK, HK, JP], interrupt_exist_connections: true}
  - {tag: OpenAI, type: selector, outbounds: [Proxy, DIY-Node, Auto-JP, JP, Auto-US, US], interrupt_exist_connections: true}
  - {tag: Google, type: selector, outbounds: [Proxy, DIY-Node,Auto-US, Select, Auto], interrupt_exist_connections: true}
  - {tag: Github, type: selector, outbounds: [Proxy, DIY-Node, Auto-SG, Select, Auto, DirectConn], interrupt_exist_connections: true}
  - {tag: Telegram, type: selector, outbounds: [Proxy, DIY-Node, Auto-SG, SG, Select], interrupt_exist_connections: true}
  - {tag: Microsoft, type: selector, outbounds: [DirectConn,Proxy, DIY-Node, SG], interrupt_exist_connections: true}
  - {tag: Apple, type: selector, outbounds: [DirectConn, Proxy, DIY-Node, Auto], interrupt_exist_connections: true}
  - {tag: Paypal, type: selector, outbounds: [Proxy, DIY-Node, Select, Auto, DirectConn], interrupt_exist_connections: true}
  - {tag: Netflix, type: selector, outbounds: [Proxy, Auto-SG, SG, Auto-HK, HK, DIY-Node ], interrupt_exist_connections: true}
  - {tag: Disney+, type: selector, outbounds: [Proxy,Auto-US, US, Auto-SG, SG, HK], interrupt_exist_connections: true}
  - {tag: HBO, type: selector, outbounds: [Proxy,Auto-US, US, Auto-HK, HK, TW], interrupt_exist_connections: true}
  - {tag: PrimeVideo, type: selector, outbounds: [Proxy,Auto-US, US, Auto-JP, JP, UK], interrupt_exist_connections: true}
  - {tag: Spotify, type: selector, outbounds: [Proxy,Auto-US, US, Auto-HK, HK, TW]}
  - {tag: TikTok, type: selector, outbounds: [Proxy,Auto-SG, SG, Auto-JP, JP, US]}
  - {tag: Steam, type: selector, outbounds: [Proxy,Auto-HK, Auto-SG, HK, SG, DirectConn]}
  - {tag: Epic, type: selector, outbounds: [Proxy,Auto-HK, HK, Auto-US, US, DirectConn]}
  - {tag: PlayStation, type: selector, outbounds: [Proxy,Auto-HK, HK, Auto-JP, JP, US]}
  - {tag: Xbox, type: selector, outbounds: [Proxy,Auto-HK, HK, Auto-SG, SG, US]}
  - {tag: BTC, type: selector, outbounds: [Auto-JP, JP, Proxy,DirectConn, Auto-SG, SG, Auto-TW, TW]}
  - {tag: HoK, type: selector, outbounds: [Auto-Game, DIY-Node, HK, JP, SG], interrupt_exist_connections: true}
  - {tag: DIY-Node, type: selector, outbounds: [ "{all}" ], filter: [ { action: include, keywords: [ "sec_" ] } ] }
  - {tag: Auto-Game,type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: [ "cr" ]}, {action: exclude, keywords: ["网站|地址|剩余|过期|时间|有效|官网|流量|sec|到期"]} ], url: https://connectivitycheck.gstatic.com/generate_204, interval: 20m, tolerance: 200, interrupt_exist_connections: false }
  - {tag: Auto-HK, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["香港|港|HK|Hong Kong|🇭🇰"]}], url: https://captive.apple.com/hotspot-detect.html, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto-JP, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["日本|日|JP|Japan|🇯🇵"]}], url: https://www.gstatic.com/generate_204, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto-US, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["美国|美國|美|US|USA|America|🇺🇸"]}], url: https://www.gstatic.com/generate_204, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto-SG, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["新加坡|狮城|獅城|坡|SG|Singapore|🇸🇬"]}], url: https://cp.cloudflare.com/generate_204, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto-TW, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["台湾|台灣|台|TW|Taiwan|🇹🇼"]}], url: https://cp.cloudflare.com/generate_204, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto-KR, type: urltest, outbounds: ["{all}"], filter: [{action: include, keywords: ["韩国|韓國|韩|KR|Korea|🇰🇷"]}], url: https://www.v2ex.com/generate_204, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Auto, type: urltest, outbounds: ["{all}"], filter: [{action: exclude, keywords: ["网站|地址|剩余|过期|时间|有效|官网|流量|sec|到期"]}], url: https://captive.apple.com/hotspot-detect.html, interval: 5m, tolerance: 100, interrupt_exist_connections: true}
  - {tag: Select, type: selector, outbounds: ["{all}"], filter: [{action: exclude, keywords: ["网站|地址|剩余|过期|时间|有效|官网|流量|sec|到期"]}]}
  - {tag: DirectConn, type: direct}
  - {tag: JP, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["日本|日|JP|Japan|🇯🇵"]}]}
  - {tag: HK, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["香港|港|HK|Hong Kong|🇭🇰"]}]}
  - {tag: US, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["美国|美國|美|US|USA|America|🇺🇸"]}]}
  - {tag: SG, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["新加坡|狮城|獅城|坡|SG|Singapore|🇸🇬"]}]}
  - {tag: UK, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["英国|英國|英|UK|Britain|🇬🇧"]}]}
  - {tag: TW, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["台湾|台灣|台|TW|Taiwan|🇹🇼"]}]}
  - {tag: KR, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["韩国|韓國|韩|KR|Korea|🇰🇷"]}]}
  - {tag: DE, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["德国|德國|德|DE|Germany|🇩🇪"]}]}
  - {tag: CA, type: selector, outbounds: ["{all}"], filter: [{action: include, keywords: ["加拿大|CA|Canada|🇨🇦"]}]}
route:
  default_domain_resolver: {server: dns_local, rewrite_ttl: 60, client_subnet: 223.5.5.5/24}
  auto_detect_interface: true
  final: Proxy
  default_mark: 1
  rules:
    - {process_name: [ "tailscaled" ], outbound: DirectConn}
    - {action: sniff}
    - {action: hijack-dns, protocol: dns }
    - {action: hijack-dns, port: 53 }
    - {ip_cidr: [ "100.64.0.0/10","fd7a:115c:a1e0::/48"],outbound: ts-node}
    - {ip_is_private: true, outbound: DirectConn}
    - {action: reject, rule_set: [geosite-ad1, geosite-ad2]}
    - {action: route, rule_set: geosite-steam, outbound: Steam}
    - {action: route, rule_set: geosite-epic, outbound: Epic}
    - {action: route, rule_set: geosite-playstation, outbound: PlayStation}
    - {action: route, rule_set: geosite-xbox, outbound: Xbox}
    - {action: route, rule_set: geosite-disney, outbound: Disney+}
    - {action: route, rule_set: geosite-hbo, outbound: HBO}
    - {action: route, rule_set: geosite-primevideo, outbound: PrimeVideo}
    - {action: route, rule_set: geosite-spotify, outbound: Spotify}
    - {action: route, rule_set: geosite-tiktok, outbound: TikTok}
    - {action: route, protocol: ssh, outbound: DirectConn}
    - {action: route, protocol: bittorrent, outbound: DirectConn}
    - {action: route, clash_mode: direct, outbound: DirectConn}
    - {action: route, clash_mode: global, outbound: Proxy}
    - {action: route, rule_set: geosite-hok, outbound: HoK}
    - {action: route, domain: [clash.razord.top, yacd.metacubex.one, yacd.haishan.me, d.metacubex.one], outbound: DirectConn}
    - {action: route, domain_suffix: [z-lib.gs, missav.com, missav.ws, follow.is, folo.is], outbound: Proxy}
    - {action: route, rule_set: geosite-cryptocurrency, outbound: BTC}
    - {action: route, rule_set: geosite-private, outbound: DirectConn}
    - {action: route, rule_set: geosite-jd, outbound: DirectConn}
    - {action: route, rule_set: geosite-ali, outbound: DirectConn }
    - {action: route, rule_set: geosite-baidu, outbound: DirectConn }
    - {action: route, rule_set: geosite-bytedance, outbound: DirectConn }
    - {action: route, rule_set: geosite-pdd, outbound: DirectConn }
    - {action: route, rule_set: geosite-bili, outbound: DirectConn }
    - { action: route, rule_set: geosite-meituan, outbound: DirectConn }
    - { action: route, rule_set: geosite-ctrip, outbound: DirectConn }
    - { action: route, rule_set: geosite-tencent, outbound: DirectConn }
    - {action: route, rule_set: geosite-ctm_cn, outbound: DirectConn}
    - {action: route, rule_set: geosite-chat, domain_suffix: [grok.com], outbound: OpenAI}
    - {action: route, rule_set: geosite-youtube, outbound: YouTube}
    - {action: route, rule_set: geosite-github, outbound: Github}
    - {action: route, rule_set: [geosite-google, geoip-google], outbound: Google}
    - {action: route, rule_set: [geosite-telegram, geoip-telegram], outbound: Telegram}
    - {action: route, rule_set: [geosite-apple, geoip-apple], outbound: Apple}
    - {action: route, rule_set: geosite-microsoft, outbound: Microsoft}
    - {action: route, rule_set: geosite-paypal, outbound: Paypal}
    - {action: route, rule_set: geosite-netflix, outbound: Netflix}
    - {action: route, rule_set: geosite-geolocation-!cn, outbound: Proxy}
    - {action: route, rule_set: [geosite-cn, geoip-cn], outbound: DirectConn}
  rule_set:
    - {tag: geosite-ad1, type: remote, format: binary, url: "{mirror_url}/https://github.com/Toperlock/sing-box-geosite/raw/main/rule/adservers.srs", download_detour: DirectConn}
    - {tag: geosite-ad2, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/privacy-protection-tools/anti-ad.github.io/master/docs/anti-ad-sing-box.srs", download_detour: DirectConn}
    - {tag: geosite-ctm_cn, type: remote, format: binary, url: "{mirror_url}/https://github.com/sixban6/rulesets/raw/refs/heads/main/rule/direct_cn.srs", download_detour: DirectConn}
    - {tag: geosite-chat, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-ai-chat-!cn.srs", download_detour: DirectConn}
    - {tag: geosite-steam, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/steam.srs", download_detour: DirectConn}
    - {tag: geosite-epic, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/epicgames.srs", download_detour: DirectConn}
    - {tag: geosite-playstation, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/sony.srs", download_detour: DirectConn}
    - {tag: geosite-xbox, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/xbox.srs", download_detour: DirectConn}
    - {tag: geosite-disney, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/disney.srs", download_detour: DirectConn}
    - {tag: geosite-hbo, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/hbo.srs", download_detour: DirectConn}
    - {tag: geosite-primevideo, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/primevideo.srs", download_detour: DirectConn}
    - {tag: geosite-spotify, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/spotify.srs", download_detour: DirectConn}
    - {tag: geosite-youtube, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/youtube.srs", download_detour: DirectConn}
    - {tag: geosite-google, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/google.srs", download_detour: DirectConn}
    - {tag: geosite-github, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/github.srs", download_detour: DirectConn}
    - {tag: geosite-telegram, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/telegram.srs", download_detour: DirectConn}
    - {tag: geosite-tiktok, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/tiktok.srs", download_detour: DirectConn}
    - {tag: geosite-netflix, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/netflix.srs", download_detour: DirectConn}
    - {tag: geosite-apple, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/apple.srs", download_detour: DirectConn}
    - {tag: geosite-microsoft, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/microsoft.srs", download_detour: DirectConn}
    - {tag: geosite-onedrive, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/onedrive.srs", download_detour: DirectConn}
    - {tag: geosite-geolocation-!cn, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/geolocation-!cn.srs", download_detour: DirectConn}
    - {tag: geosite-cn, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/cn.srs", download_detour: DirectConn}
    - {tag: geosite-private, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/private.srs", download_detour: DirectConn}
    - {tag: geoip-google, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/google.srs", download_detour: DirectConn}
    - {tag: geoip-telegram, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/telegram.srs", download_detour: DirectConn}
    - {tag: geoip-netflix, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/netflix.srs", download_detour: DirectConn}
    - {tag: geoip-apple, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo-lite/geoip/apple.srs", download_detour: DirectConn}
    - {tag: geoip-cn, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/cn.srs", download_detour: DirectConn}
    - {tag: geoip-private, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/private.srs", download_detour: DirectConn}
    - {tag: geosite-paypal, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/paypal.srs", download_detour: DirectConn}
    - {tag: geosite-hok, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/sixban6/rulesets/refs/heads/main/rule/hok.srs", download_detour: DirectConn}
    - {tag: geosite-cryptocurrency, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-cryptocurrency.srs", download_detour: DirectConn}
    - {tag: geosite-jd, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/jd.srs", download_detour: DirectConn }
    - {tag: geosite-ali, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/alibaba.srs", download_detour: DirectConn }
    - {tag: geosite-baidu, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/baidu.srs", download_detour: DirectConn }
    - {tag: geosite-bytedance, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/bytedance.srs", download_detour: DirectConn }
    - {tag: geosite-pdd, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/pinduoduo.srs", download_detour: DirectConn }
    - {tag: geosite-bili, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/bilibili.srs", download_detour: DirectConn }
    - {tag: geosite-meituan, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/meituan.srs", download_detour: DirectConn }
    - {tag: geosite-ctrip, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/ctrip.srs", download_detour: DirectConn }
    - {tag: geosite-tencent, type: remote, format: binary, url: "{mirror_url}/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/tencent.srs", download_detour: DirectConn }
certificate:
  store: mozilla
endpoints:
   - {type: tailscale, tag: ts-node, auth_key: ts_auth_key, ephemeral: false,system_interface: false,system_interface_name: "",accept_routes: true,advertise_routes: [ts_lan_ipcidr]}
